// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: trivyapi/proto/trivy.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение запроса для отправки zip-файла
type ZipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *ZipRequest) Reset() {
	*x = ZipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trivyapi_proto_trivy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZipRequest) ProtoMessage() {}

func (x *ZipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivyapi_proto_trivy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZipRequest.ProtoReflect.Descriptor instead.
func (*ZipRequest) Descriptor() ([]byte, []int) {
	return file_trivyapi_proto_trivy_proto_rawDescGZIP(), []int{0}
}

func (x *ZipRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Сообщение запроса для отправки массива строк
type ImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trivyapi_proto_trivy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trivyapi_proto_trivy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_trivyapi_proto_trivy_proto_rawDescGZIP(), []int{1}
}

func (x *ImageRequest) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

// Сообщение ответа для обоих методов
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success       bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TrivyResponse *TrivyResponse `protobuf:"bytes,2,opt,name=trivy_response,json=trivyResponse,proto3" json:"trivy_response,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trivyapi_proto_trivy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_trivyapi_proto_trivy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_trivyapi_proto_trivy_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetTrivyResponse() *TrivyResponse {
	if x != nil {
		return x.TrivyResponse
	}
	return nil
}

// Сообщение для TrivyResponse
type TrivyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Results `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *TrivyResponse) Reset() {
	*x = TrivyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trivyapi_proto_trivy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrivyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrivyResponse) ProtoMessage() {}

func (x *TrivyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trivyapi_proto_trivy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrivyResponse.ProtoReflect.Descriptor instead.
func (*TrivyResponse) Descriptor() ([]byte, []int) {
	return file_trivyapi_proto_trivy_proto_rawDescGZIP(), []int{3}
}

func (x *TrivyResponse) GetResults() []*Results {
	if x != nil {
		return x.Results
	}
	return nil
}

// Сообщение для Results
type Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vulnerabilities []*Vulnerabilities `protobuf:"bytes,1,rep,name=vulnerabilities,proto3" json:"vulnerabilities,omitempty"`
	Image           string             `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Results) Reset() {
	*x = Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trivyapi_proto_trivy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Results) ProtoMessage() {}

func (x *Results) ProtoReflect() protoreflect.Message {
	mi := &file_trivyapi_proto_trivy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Results.ProtoReflect.Descriptor instead.
func (*Results) Descriptor() ([]byte, []int) {
	return file_trivyapi_proto_trivy_proto_rawDescGZIP(), []int{4}
}

func (x *Results) GetVulnerabilities() []*Vulnerabilities {
	if x != nil {
		return x.Vulnerabilities
	}
	return nil
}

func (x *Results) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// Сообщение для Vulnerabilities
type Vulnerabilities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VulnerabilityId string `protobuf:"bytes,1,opt,name=vulnerability_id,json=vulnerabilityId,proto3" json:"vulnerability_id,omitempty"`
	PkgId           string `protobuf:"bytes,2,opt,name=pkg_id,json=pkgId,proto3" json:"pkg_id,omitempty"`
	Title           string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Severity        string `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
}

func (x *Vulnerabilities) Reset() {
	*x = Vulnerabilities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trivyapi_proto_trivy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vulnerabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerabilities) ProtoMessage() {}

func (x *Vulnerabilities) ProtoReflect() protoreflect.Message {
	mi := &file_trivyapi_proto_trivy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vulnerabilities.ProtoReflect.Descriptor instead.
func (*Vulnerabilities) Descriptor() ([]byte, []int) {
	return file_trivyapi_proto_trivy_proto_rawDescGZIP(), []int{5}
}

func (x *Vulnerabilities) GetVulnerabilityId() string {
	if x != nil {
		return x.VulnerabilityId
	}
	return ""
}

func (x *Vulnerabilities) GetPkgId() string {
	if x != nil {
		return x.PkgId
	}
	return ""
}

func (x *Vulnerabilities) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Vulnerabilities) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

var File_trivyapi_proto_trivy_proto protoreflect.FileDescriptor

var file_trivyapi_proto_trivy_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x72, 0x69, 0x76, 0x79, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x72, 0x69, 0x76, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x72,
	0x69, 0x76, 0x79, 0x22, 0x22, 0x0a, 0x0a, 0x5a, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x22, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x61, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x3b, 0x0a, 0x0e, 0x74, 0x72, 0x69, 0x76, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x72, 0x69, 0x76,
	0x79, 0x2e, 0x54, 0x72, 0x69, 0x76, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x0d, 0x74, 0x72, 0x69, 0x76, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39,
	0x0a, 0x0d, 0x54, 0x72, 0x69, 0x76, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x74, 0x72, 0x69, 0x76, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x61, 0x0a, 0x07, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x40, 0x0a, 0x0f, 0x76, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x74, 0x72, 0x69, 0x76, 0x79, 0x2e, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0f, 0x76, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x85, 0x01, 0x0a,
	0x0f, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x29, 0x0a, 0x10, 0x76, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x75, 0x6c, 0x6e,
	0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x70,
	0x6b, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6b, 0x67,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x32, 0x79, 0x0a, 0x0c, 0x54, 0x72, 0x69, 0x76, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x11, 0x2e, 0x74, 0x72, 0x69, 0x76, 0x79, 0x2e, 0x5a, 0x69, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x74, 0x72, 0x69, 0x76, 0x79, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x33, 0x0a, 0x0b, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x74, 0x72, 0x69, 0x76,
	0x79, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f,
	0x2e, 0x74, 0x72, 0x69, 0x76, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x14, 0x5a, 0x12, 0x74, 0x72, 0x69, 0x76, 0x79, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trivyapi_proto_trivy_proto_rawDescOnce sync.Once
	file_trivyapi_proto_trivy_proto_rawDescData = file_trivyapi_proto_trivy_proto_rawDesc
)

func file_trivyapi_proto_trivy_proto_rawDescGZIP() []byte {
	file_trivyapi_proto_trivy_proto_rawDescOnce.Do(func() {
		file_trivyapi_proto_trivy_proto_rawDescData = protoimpl.X.CompressGZIP(file_trivyapi_proto_trivy_proto_rawDescData)
	})
	return file_trivyapi_proto_trivy_proto_rawDescData
}

var file_trivyapi_proto_trivy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_trivyapi_proto_trivy_proto_goTypes = []any{
	(*ZipRequest)(nil),      // 0: trivy.ZipRequest
	(*ImageRequest)(nil),    // 1: trivy.ImageRequest
	(*Response)(nil),        // 2: trivy.Response
	(*TrivyResponse)(nil),   // 3: trivy.TrivyResponse
	(*Results)(nil),         // 4: trivy.Results
	(*Vulnerabilities)(nil), // 5: trivy.Vulnerabilities
}
var file_trivyapi_proto_trivy_proto_depIdxs = []int32{
	3, // 0: trivy.Response.trivy_response:type_name -> trivy.TrivyResponse
	4, // 1: trivy.TrivyResponse.results:type_name -> trivy.Results
	5, // 2: trivy.Results.vulnerabilities:type_name -> trivy.Vulnerabilities
	0, // 3: trivy.TrivyService.UploadStream:input_type -> trivy.ZipRequest
	1, // 4: trivy.TrivyService.UploadImage:input_type -> trivy.ImageRequest
	2, // 5: trivy.TrivyService.UploadStream:output_type -> trivy.Response
	2, // 6: trivy.TrivyService.UploadImage:output_type -> trivy.Response
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_trivyapi_proto_trivy_proto_init() }
func file_trivyapi_proto_trivy_proto_init() {
	if File_trivyapi_proto_trivy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trivyapi_proto_trivy_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ZipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trivyapi_proto_trivy_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trivyapi_proto_trivy_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trivyapi_proto_trivy_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TrivyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trivyapi_proto_trivy_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trivyapi_proto_trivy_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Vulnerabilities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trivyapi_proto_trivy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trivyapi_proto_trivy_proto_goTypes,
		DependencyIndexes: file_trivyapi_proto_trivy_proto_depIdxs,
		MessageInfos:      file_trivyapi_proto_trivy_proto_msgTypes,
	}.Build()
	File_trivyapi_proto_trivy_proto = out.File
	file_trivyapi_proto_trivy_proto_rawDesc = nil
	file_trivyapi_proto_trivy_proto_goTypes = nil
	file_trivyapi_proto_trivy_proto_depIdxs = nil
}
